### ISSUE TITLE
Where is the released .snap package ?

### ISSUE THREAD

**Issue by kewix** [liberavia/3CXClientSnap#1]
Hello firstly, thanks for your work ! I was waiting this for a long time.
Can you tell me where I can download your snap ? I don't see it on github page
Do I have to use snapcraft ?

Thanks !

**Comment by liberavia** [comment]
Sorry for late responding,

I simply missed the notification it seems. However the snap can be found in the releases tab:
https://github.com/liberavia/3CXClientSnap/releases
